# Generated by Django 5.0.2 on 2024-05-02 10:27

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='architecture',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temple',
            name='history',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temple',
            name='opening_closing_time',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='temple',
            name='significance',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
