# Generated by Django 5.0.2 on 2024-05-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_temple_architecture_temple_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='description',
            field=models.TextField(),
        ),
    ]
