# Generated by Django 5.0.2 on 2024-05-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_temple_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='architecture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temple',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='temple',
            name='significance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
