# Generated by Django 5.0.2 on 2024-05-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_temple_architecture_alter_temple_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temple',
            name='opening_closing_time',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
