# Generated by Django 5.0.2 on 2024-05-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_temple_opening_closing_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temple',
            name='toreach',
            field=models.TextField(blank=True, null=True),
        ),
    ]
