# Generated by Django 5.0.2 on 2024-05-02 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_temple_toreach'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temple',
            old_name='toreach',
            new_name='howtoreach',
        ),
    ]
